### ISSUE TITLE
Need to update Rcpp

### ISSUE THREAD

**Issue by romainjouin** [earthlab/dockerfiles#1]
I couldn't load tensorflow and had an Rcpp version compatibility issue.

Thanks to  : https://github.com/rstudio/tensorflow/issues/12
I did : 

install.packages("Rcpp")
.rs.restartR()

And then it worked.
Maybe update Rcpp directly in the docker file ?

**Comment by mbjoseph** [comment]
I just rebuilt using the same Dockerfile via `docker build` and tensorflow seems to load just fine. Can you try to pull down the image from Docker Hub and try again?

**Comment by romainjouin** [comment]
We just had again the same issue : 
library(tensorflow)
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘Rcpp’ 0.12.6 is already loaded, but >= 0.12.7 is required
Error: package or namespace load failed for ‘tensorflow’

**Comment by mbjoseph** [comment]
That's strange @romainjouin - in the most recent image Rcpp version 0.12.10 is installed, not 0.12.6. I'm not sure where that version would be coming from. 

Are you sure that you pulled the image down from Docker Hub? e.g., 

```
docker pull earthlab/r-tensorflow
docker run -d -p 8787:8787 earthlab/r-tensorflow
```

Then navigate to localhost:8787 in your web browser (un/pw is rstudio/rstudio)
