### ISSUE TITLE
r-greta no tensorflow-probability installed, and install_tensorflow(extra_packages = "tensorflow-probability")  does not resolve the issue

### ISSUE THREAD

**Issue by thorvall** [earthlab/dockerfiles#10]
Thanks for providing a greta enable container. Choose yours to avoid the errors the is common when installing tensorflow-probability with greta.

unfortunately the current version suffer from the same problems.

After running:
install_tensorflow(extra_packages = "tensorflow-probability") 

Restarting R session...
> library(greta)
greta requires TensorFlow (>=1.10.0) and Tensorflow Probability (>=0.3.0), but TensorFlow Probability isn't installed. Use:
install_tensorflow(extra_packages = "tensorflow-probability") 
to install the latest version.

**Comment by thorvall** [comment]
using the procedure from this link, solves the issue. But i have no idea as how to implement this in the docker file:
https://github.com/greta-dev/greta/issues/255#issuecomment-441033840

---
login to docker client, shift to rstudio user home dir:
anh@anh ~ $  .  .virtualenvs/r-tensorflow/bin/activate 
(r-tensorflow) anh@anh ~ $ pip install -U tensorflow
(r-tensorflow) anh@anh ~ $ pip install -U tensorflow-probability

**Comment by mbjoseph** [comment]
Thanks @thorvall for opening this issue! Solved by a558319
