### ISSUE TITLE
Can't import geopandas/fiona with spatial-python

### ISSUE THREAD

**Issue by jdiaz4302** [earthlab/dockerfiles#11]
Brand new pull of the environment can't import geopandas/fiona. I've been trying to get it fixed for a while today with no luck. Below is result of "import geopandas"

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-fc7d1d298f0c> in <module>
----> 1 import geopandas

/opt/conda/lib/python3.6/site-packages/geopandas/__init__.py in <module>
      2 from geopandas.geodataframe import GeoDataFrame
      3 
----> 4 from geopandas.io.file import read_file
      5 from geopandas.io.sql import read_postgis
      6 from geopandas.tools import sjoin

/opt/conda/lib/python3.6/site-packages/geopandas/io/file.py in <module>
      1 import os
      2 
----> 3 import fiona
      4 import numpy as np
      5 import six

/opt/conda/lib/python3.6/site-packages/fiona/__init__.py in <module>
     81     os.environ["PATH"] = os.environ["PATH"] + ";" + libdir
     82 
---> 83 from fiona.collection import BytesCollection, Collection
     84 from fiona.drvsupport import supported_drivers
     85 from fiona.env import ensure_env_with_credentials, Env

/opt/conda/lib/python3.6/site-packages/fiona/collection.py in <module>
      7 
      8 from fiona import compat, vfs
----> 9 from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
     10 from fiona.ogrext import Session, WritingSession
     11 from fiona.ogrext import buffer_to_virtual_file, remove_virtual_file, GEOMETRY_TYPES

ImportError: /opt/conda/lib/python3.6/site-packages/fiona/../../../libgdal.so.20: undefined symbol: _ZN6libdap3DDSC1EPNS_15BaseTypeFactoryERKSs

**Comment by jdiaz4302** [comment]
Similarly, fails to import osr with same apparent culprit

ImportError                               Traceback (most recent call last)
<ipython-input-1-2093c17effff> in <module>
      5 import numpy as np
      6 from netCDF4 import Dataset
----> 7 import osr
      8 import matplotlib.pyplot as plt

/opt/conda/lib/python3.6/site-packages/osr.py in <module>
      1 # import osgeo.osr as a convenience
----> 2 from osgeo.gdal import deprecation_warn
      3 deprecation_warn('osr')
      4 
      5 from osgeo.osr import *

/opt/conda/lib/python3.6/site-packages/osgeo/__init__.py in <module>
     19                 fp.close()
     20             return _mod
---> 21     _gdal = swig_import_helper()
     22     del swig_import_helper
     23 else:

/opt/conda/lib/python3.6/site-packages/osgeo/__init__.py in swig_import_helper()
     15         if fp is not None:
     16             try:
---> 17                 _mod = imp.load_module('_gdal', fp, pathname, description)
     18             finally:
     19                 fp.close()

/opt/conda/lib/python3.6/imp.py in load_module(name, file, filename, details)
    241                 return load_dynamic(name, filename, opened_file)
    242         else:
--> 243             return load_dynamic(name, filename, file)
    244     elif type_ == PKG_DIRECTORY:
    245         return load_package(name, filename)

/opt/conda/lib/python3.6/imp.py in load_dynamic(name, path, file)
    341         spec = importlib.machinery.ModuleSpec(
    342             name=name, loader=loader, origin=path)
--> 343         return _load(spec)
    344 
    345 else:

ImportError: /opt/conda/lib/python3.6/site-packages/osgeo/../../../libgdal.so.20: undefined symbol: _ZN6libdap3DDSC1EPNS_15BaseTypeFactoryERKSs

**Comment by mbjoseph** [comment]
Thanks @jdiaz4302 - which Docker image is this issue referring to? Maybe earthlab/spatial-python?

**Comment by jdiaz4302** [comment]
@mbjoseph Yeah, earthlab/spatial-python

It's not urgent (for me) because I got my project needs by the earth analytics environment

**Comment by mbjoseph** [comment]
Great - fixed in https://github.com/earthlab/dockerfiles/commit/79d295f03488f1a3783637a7d7e63f89b0783207
